### ISSUE TITLE
react-router Issues

### ISSUE THREAD

**Issue by rrcampbell-exe** [rrcampbell-exe/ryan-r-campbell#62]
Consider having anything that comes after the URL for a blog post removed from the URL so that it correctly routes visitors to the blog post in question. Specifically, the inclusion of `amp` in a URL after the blog post's params (as indexed by Google) will cause redirects to the `NotFound` component.

You should also look into mapping over paths and having them direct to a single element. For example, `books/imminent-dawn` on the old site should just send you to `books#imminent-dawn` instead.

**Comment by Gitstar-OC** [comment]
Hey I would like to fix this issue, assign it to me and I will code it out!


## Also checkout my [React Notes](https://github.com/Gitstar-OC/React-Notes) and in progress [Machine Learning](https://github.com/Gitstar-OC/Machine-Learning) notes if you want to progress or contribute! 

Happy Coding :)

**Comment by rrcampbell-exe** [comment]
Thanks for reaching out, but with this being a personal portfolio project, it's important I maintain full ownership for its content and codebase. Wishing you continued success on your machine learning journey!

**Comment by rrcampbell-exe** [comment]
This issue has been resolved. Remaining bonus feature work/bugs discovered during regression testing:

- Have router look at any params passed after /books and treat them as a hash, redirecting to corresponding anchor tag
- "reviews" anchor tag on books landing page is broken
- move Ryan R. Campbell to top of projects list on tech landing page

**Comment by rrcampbell-exe** [comment]
All of this has been resolved except for 

- Have router look at any params passed after /books and treat them as a hash, redirecting to corresponding anchor tag

This will be put into a separate issue and addressed at a later date.
